### ISSUE TITLE
NFC not working

### ISSUE THREAD

**Issue by DanWard** [Verevka/android_device_xiaomi_sagit#1]
Hi there,

Upon compiling this build with the China Dev 7.7.7 fastboot firmware, the NFC does not work. 
This is what happens when opening settings: https://imgur.com/a/FMbxU.
I have looked through the logcat but can only see:

> 07-17 21:45:34.467   681   681 I ServiceManager: service 'nfc' died
> 07-17 21:45:34.468  1257  1296 I ActivityManager: Process com.android.nfc (pid 12207) has died
> 07-17 21:45:34.468  1257  1296 D ActivityManager: cleanUpApplicationRecord -- 12207
> 07-17 21:45:34.469  1257  1296 W ActivityManager: Re-adding persistent process ProcessRecord{ed9c338 12207:com.android.nfc/1027}
> 07-17 21:45:34.471   718   718 I Zygote  : Process 12207 exited due to signal (6)
> 07-17 21:45:34.480  1257  1296 I ActivityManager: Start proc 12602:com.android.nfc/1027 for restart com.android.nfc

Many thanks,
Daniel

**Comment by Verevka** [comment]
you are using my- libnfc-brcm.conf ?

**Comment by DanWard** [comment]
Yep, I'm compiling cleanly from your repo with your local manifest. 
I got this from the dmesg:

sagit:/ $ dmesg | grep nfc
[    0.870309] nq-nci 6-0028: nfcc_hw_check: - nq - reset cmd answer : NfcNciRx 40 0 3
[    5.371488] init: property_set("ro.nfc.port", "I2C") failed
[    5.392018] init: Starting service 'nqnfcinfo'...
[    5.415785] init: Service 'nqnfcinfo' (pid 735) exited with status 1
sagit:/ $

Sorry for the formatting, I'm on mobile. 

Daniel

**Comment by Verevka** [comment]
don't know how to help yet, I'll try to compile with the vendor 7.7.7, later I'll write what I got.

**Comment by DanWard** [comment]
Interestingly enough NfcService:mRoutingWakeLock is holding the phone awake almost all of the time. 
I might have to try and use the older firmware. 

Daniel

**Comment by zuizhongye** [comment]
Why I compiled ROM  /lib/modules directory only wlan.ko @Verevka

**Comment by DanWard** [comment]
@verevka I've compiled with 7.7.20 and it still doesn't work. I've also installed your latest rom from AndroidFileHost and NFC still breaks. 
I'm not sure what logs I can give you that will help? I have full logcat and dmesg.

**Comment by Verevka** [comment]
I took the vendor 7.7.20 and I have all worked. Firmware compiled for 7.6.29.
 At least I think you need to use too 7.7.20. https://github.com/Verevka/proprietary_vendor_xiaomi_sagit/blob/cm-14.1/proprietary/vendor/firmware/libpn553_fw.so
