### ISSUE TITLE
wifi mac is random

### ISSUE THREAD

**Issue by coderstory** [Verevka/android_device_xiaomi_sagit#11]
readmac module is not available
wifi mac address will change after boot or reboot
wlan.ko maybe not read wlan_mac.bin

···
[   21.829000] R0: [kworker/u16:3][471746754] [22:00:39.696921]  wlan: [334:E :HDD] hdd_ipa_uc_register_uc_ready:726: UC Ready
[   21.829021] R0: [kworker/u16:3][471747234] [22:00:39.696946]  wlan: [334:E :HDD] hdd_update_config_from_nv: 7987: Invalid MAC in NV file
[   21.834151] R0: [kworker/u16:3][471845684] [22:00:39.702073]  wlan: [334:E :HDD] wlan_hdd_gen_wlan_status_pack: 78: invalid session id: 255
···

**Comment by Verevka** [comment]
Hello coderstory,  you can give your email, I need to consult with you.

**Comment by coderstory** [comment]
coderstory at 163.com

**Comment by Verevka** [comment]
Fix
