### ISSUE TITLE
lack libmorpho_groupshot.so 

### ISSUE THREAD

**Issue by coderstory** [Verevka/android_device_xiaomi_sagit#14]
can't loadLibrary, dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/MiuiCamera/MiuiCamera.apk"],nativeLibraryDirectories=[/system/priv-app/MiuiCamera/lib/arm64, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]] couldn't find "libmorpho_groupshot.so"

**Comment by Verevka** [comment]
Yes thanks, I have corrected it.
