### ISSUE TITLE
Gallery Crashed 

### ISSUE THREAD

**Issue by coderstory** [Verevka/android_device_xiaomi_sagit#15]
open gallery
open  a picture
click  button about edit picture
do some change
click back button
close gallery without save
the gallery  is crash

09-16 21:31:45.670  2337  2337 E QtiImsExtUtils: getConfigForPhoneId phoneId is invalid
09-16 21:31:45.670  2337  2337 E QtiImsExtUtils: isCarrierConfigEnabled bundle is null
09-16 21:31:48.188 12664 12664 E art     : No implementation found for void com.android.gallery3d.filtershow.tools.DualCameraEffect.release() (tried Java_com_android_gallery3d_filtershow_tools_DualCameraEffect_release and Java_com_android_gallery3d_filtershow_tools_DualCameraEffect_release__)
09-16 21:31:48.189 12664 12664 E AndroidRuntime: FATAL EXCEPTION: main
09-16 21:31:48.189 12664 12664 E AndroidRuntime: Process: com.android.gallery3d, PID: 12664
09-16 21:31:48.189 12664 12664 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.android.gallery3d.filtershow.tools.DualCameraEffect.release() (tried Java_com_android_gallery3d_filtershow_tools_DualCameraEffect_release and Java_com_android_gallery3d_filtershow_tools_DualCameraEffect_release__)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at com.android.gallery3d.filtershow.tools.DualCameraEffect.release(Native Method)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at com.android.gallery3d.filtershow.FilterShowActivity.onDestroy(FilterShowActivity.java:1963)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at android.app.Activity.performDestroy(Activity.java:6886)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4227)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at android.app.ActivityThread.-wrap6(ActivityThread.java)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-16 21:31:48.189 12664 12664 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by fahmi182** [comment]
So, better using google photos as default, so mean.. we are not using gallery again? default camera and google photos is good now.

**Comment by coderstory** [comment]
in chinese.  google can not access. .......

**Comment by fahmi182** [comment]
Oh, i see, so we must enable again Gallery default with google photos 👍

**Comment by Verevka** [comment]
Look at here- https://github.com/sultanxda/patcher/tree/cm-14.1-oneplus3/custom

**Comment by coderstory** [comment]
not  available for this problem....

**Comment by Verevka** [comment]
Look at here- 
https://github.com/sultanxda/android/blob/master/oneplus3/cm-14.1/local_manifest.xml
Gallery2 is used from cm-13.0
