### ISSUE TITLE
Camera number bug?

### ISSUE THREAD

**Issue by Ricky-Hao** [Verevka/android_device_xiaomi_sagit#3]
* OS: LineageOS b2/b3, RR(0810)
* Problem: 
In camera app, there are 4 camera could be swtched. 
In order:
2xCamera, 1xCamera, 1xCamera, FrontCamera
So, is this a bug that it has 4 camera?

**Comment by fahmi182** [comment]
Maybe its because camera media_profiles have 4 ID, 0,1,2,3 check here:
https://github.com/Verevka/android_device_xiaomi_sagit/blob/AICP-12.1/configs/media_profiles.xml
