### ISSUE TITLE
wifi is not working  on lineage os

### ISSUE THREAD

**Issue by coderstory** [Verevka/android_device_xiaomi_sagit#5]
wifi is not wordking
the wifi mac address is 02000000

**Comment by coderstory** [comment]
08-21 10:19:56.033  1360  2001 E WifiMonitor: killSupplicant p2ptrue init.svc.wpa_supplicant=unknown init.svc.p2p_supplicant=unknown
08-21 10:19:56.141  1360  2001 E WifiStateMachine: Failed to load driver
08-21 10:19:56.142  1360  1360 E WifiController: WifiControllerWifi turn on failed
08-21 10:19:56.143   764   764 E Parcel  : Reading a NULL string not supported here.
08-21 10:19:56.143   764   764 E Parcel  : Reading a NULL string not supported here.
08-21 10:19:56.143   764   764 E Parcel  : Reading a NULL string not supported here.
08-21 10:19:56.143   764   764 E Parcel  : Reading a NULL string not supported here.

**Comment by coderstory** [comment]
WifiHW  : finit_module for "/system/lib/modules/wlan.ko" failed: Required key not available

**Comment by Verevka** [comment]
Have you updated the firmware to version 7.8.17?

**Comment by coderstory** [comment]
i check it。
kernel  is 8.18 alpha
blobs is 8.17 dev
replace wlan.ko with dev
wifi is working now

**Comment by Verevka** [comment]
I already did, why not disembarked commits
