### ISSUE TITLE
deep sleep with cpu is not available

### ISSUE THREAD

**Issue by coderstory** [Verevka/android_device_xiaomi_sagit#8]
lineage os
use kernel adiutor
![w](http://ww2.sinaimg.cn/large/0060lm7Tgy1firjayxm1ij30u01hcjw6.jpg)

**Comment by Verevka** [comment]
![screenshot_20170821-134828](https://user-images.githubusercontent.com/2996364/29516051-9b0bc11a-8677-11e7-96bb-04e0ff516da3.png)
On my AICP okay, I don't use lineage, maybe it's because XiaomiDoze.

**Comment by Verevka** [comment]
I am very glad for your help, thank you very much!!! My knowledge of github for this may be errors.

**Comment by coderstory** [comment]
Deep sleep occurs only when the screen is closed
I did not turn off the screen after the boot 
so no deep sleep
